const Provider_Loc = () => {
    return ( 
        <div className="lorem">
            <h1>Provider Locator</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nibh cras pulvinar mattis nunc sed. Aliquam etiam erat velit scelerisque in dictum. Magna eget est lorem ipsum dolor sit amet consectetur. Donec enim diam vulputate ut pharetra. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Lobortis elementum nibh tellus molestie. Tincidunt ornare massa eget egestas. Sit amet risus nullam eget felis eget. Enim sed faucibus turpis in eu mi bibendum neque. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Amet consectetur adipiscing elit pellentesque.</p>

            <p>Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Nec dui nunc mattis enim ut tellus. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Risus nec feugiat in fermentum posuere. Non blandit massa enim nec dui nunc mattis. Tempus imperdiet nulla malesuada pellentesque elit eget. Quis lectus nulla at volutpat diam ut venenatis tellus. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Lacinia at quis risus sed vulputate odio ut enim.</p>

            <p>Facilisis mauris sit amet massa vitae tortor. Leo duis ut diam quam nulla porttitor massa. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Accumsan in nisl nisi scelerisque eu. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Mus mauris vitae ultricies leo integer malesuada. Massa vitae tortor condimentum lacinia quis vel eros. Mi quis hendrerit dolor magna. Dictum at tempor commodo ullamcorper a. Egestas dui id ornare arcu odio. Enim diam vulputate ut pharetra sit amet. Imperdiet sed euismod nisi porta lorem mollis aliquam. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Leo duis ut diam quam nulla. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Bibendum neque egestas congue quisque egestas diam in. A iaculis at erat pellentesque adipiscing commodo elit at. Enim sed faucibus turpis in.</p>

            <p>Netus et malesuada fames ac turpis egestas maecenas. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Aliquam id diam maecenas ultricies mi. Vitae elementum curabitur vitae nunc sed velit dignissim. Tristique et egestas quis ipsum suspendisse. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Massa id neque aliquam vestibulum morbi blandit cursus risus. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Adipiscing diam donec adipiscing tristique. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat.</p>

            <p>Mi proin sed libero enim sed faucibus turpis in. Est ullamcorper eget nulla facilisi etiam. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Ac tincidunt vitae semper quis lectus nulla at. Elementum integer enim neque volutpat. Blandit libero volutpat sed cras ornare. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Tortor condimentum lacinia quis vel eros donec. Ut venenatis tellus in metus vulputate. Egestas diam in arcu cursus euismod quis. Amet commodo nulla facilisi nullam vehicula ipsum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Elit scelerisque mauris pellentesque pulvinar pellentesque.</p>

            <p>Mi quis hendrerit dolor magna eget. Mi quis hendrerit dolor magna eget est. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Ultrices eros in cursus turpis massa tincidunt dui. Imperdiet dui accumsan sit amet nulla. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Accumsan sit amet nulla facilisi morbi tempus iaculis. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Quis hendrerit dolor magna eget est lorem.</p>
        </div>
     );
}
 
export default Provider_Loc;