const Symptom_Checker = () => {
    return ( 
        <div className="lorem">
            <h1>Symptom Checker</h1>
            <p>Eu scelerisque felis imperdiet proin fermentum leo vel. Eu sem integer vitae justo eget. Vel turpis nunc eget lorem dolor. Nisl rhoncus mattis rhoncus urna. Pretium quam vulputate dignissim suspendisse in. Ultricies leo integer malesuada nunc. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Egestas integer eget aliquet nibh praesent tristique magna sit. Pellentesque eu tincidunt tortor aliquam nulla. Pretium quam vulputate dignissim suspendisse. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum.</p>

            <p>Felis bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis. Tincidunt dui ut ornare lectus sit amet. Vitae elementum curabitur vitae nunc. Urna et pharetra pharetra massa massa ultricies mi. Consequat interdum varius sit amet mattis vulputate enim. Commodo ullamcorper a lacus vestibulum sed. Quisque egestas diam in arcu cursus euismod quis. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Sem et tortor consequat id porta. Facilisi cras fermentum odio eu feugiat pretium. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Lacus sed turpis tincidunt id aliquet. Praesent tristique magna sit amet purus gravida quis blandit. Leo vel orci porta non pulvinar. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Vitae et leo duis ut diam quam nulla.</p>

            <p>Justo laoreet sit amet cursus sit amet dictum sit amet. Aliquam etiam erat velit scelerisque in dictum. Magna fringilla urna porttitor rhoncus dolor purus non. Ut faucibus pulvinar elementum integer enim neque volutpat. Tortor dignissim convallis aenean et tortor at risus. Facilisi cras fermentum odio eu. Sed id semper risus in hendrerit. Consequat ac felis donec et odio pellentesque diam volutpat. Ac orci phasellus egestas tellus. Vestibulum rhoncus est pellentesque elit. Commodo odio aenean sed adipiscing diam donec adipiscing. Nunc non blandit massa enim. Eget aliquet nibh praesent tristique magna sit amet purus. Enim lobortis scelerisque fermentum dui. Erat pellentesque adipiscing commodo elit. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Malesuada fames ac turpis egestas sed tempus urna. Imperdiet dui accumsan sit amet nulla facilisi morbi. Nunc sed velit dignissim sodales ut eu. Fusce ut placerat orci nulla pellentesque dignissim enim.</p>

            <p>Vivamus at augue eget arcu dictum varius duis at. Etiam erat velit scelerisque in dictum non consectetur a. Viverra adipiscing at in tellus integer. Nibh praesent tristique magna sit amet purus. Ultrices neque ornare aenean euismod elementum nisi. Et leo duis ut diam quam nulla porttitor massa id. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Commodo odio aenean sed adipiscing diam donec adipiscing. Sed velit dignissim sodales ut eu sem integer vitae. Gravida cum sociis natoque penatibus et magnis dis parturient montes. At lectus urna duis convallis convallis tellus id interdum. Aliquam faucibus purus in massa tempor nec feugiat. Amet est placerat in egestas erat imperdiet.</p>

            <p>Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Nec dui nunc mattis enim ut tellus. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Risus nec feugiat in fermentum posuere. Non blandit massa enim nec dui nunc mattis. Tempus imperdiet nulla malesuada pellentesque elit eget. Quis lectus nulla at volutpat diam ut venenatis tellus. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Lacinia at quis risus sed vulputate odio ut enim.</p>

            <p>Netus et malesuada fames ac turpis egestas maecenas. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Aliquam id diam maecenas ultricies mi. Vitae elementum curabitur vitae nunc sed velit dignissim. Tristique et egestas quis ipsum suspendisse. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Massa id neque aliquam vestibulum morbi blandit cursus risus. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Adipiscing diam donec adipiscing tristique. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat.</p>
        </div>
     );
}
 
export default Symptom_Checker;